import { z } from "zod";

const KNOWN_DEV_JWT_SECRET = "dev_jwt_secret_k8xP2mQ9vR3nT6wY1bF4hJ7dL0cA5eG";

const envSchema = z.object({
  appId: z.string().optional().default(""),
  cookieSecret: z.string().optional().default(""),
  databaseUrl: z.string().optional().default(""),
  oAuthServerUrl: z.string().optional().default(""),
  ownerOpenId: z.string().optional().default(""),
  /** Self-hosted admin login (alternative to OAuth): username for the single admin account. */
  adminUsername: z.string().optional().default(""),
  /** Self-hosted admin login: scrypt hash in the scripts/hashPassword.mjs format. */
  adminPasswordHash: z.string().optional().default(""),
  isProduction: z.boolean(),
  forgeApiUrl: z.string().optional().default(""),
  forgeApiKey: z.string().optional().default(""),
  turnstileSecretKey: z.string().optional().default(""),
  turnstileAllowTestKey: z.coerce.boolean(),
  /** AES-256-GCM key for PII field encryption (UU PDP compliance). Optional but strongly recommended in production. */
  piiEncryptionKey: z.string().optional().default(""),
  /**
   * Comma-separated PII encryption key ring (rotation support). The FIRST entry
   * is the primary key used for encryption; the rest are retired keys kept so
   * old ciphertext still decrypts. Takes precedence over piiEncryptionKey.
   */
  piiEncryptionKeys: z.string().optional().default(""),
  /** Redis/Dragonfly connection URL for distributed rate limiting. Optional; falls back to in-memory. */
  redisUrl: z.string().optional().default(""),
  /** Emergency escape hatch: launch production with plaintext PII when the encryption key cannot yet be provisioned. */
  allowPlaintextPii: z.coerce.boolean().optional().default(false),
});

const parsedEnv = envSchema.parse({
  appId: process.env.VITE_APP_ID,
  cookieSecret: process.env.JWT_SECRET,
  databaseUrl: process.env.DATABASE_URL,
  oAuthServerUrl: process.env.OAUTH_SERVER_URL,
  ownerOpenId: process.env.OWNER_OPEN_ID,
  adminUsername: process.env.ADMIN_USERNAME,
  adminPasswordHash: process.env.ADMIN_PASSWORD_HASH,
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL,
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY,
  turnstileSecretKey: process.env.TURNSTILE_SECRET_KEY,
  turnstileAllowTestKey: process.env.TURNSTILE_ALLOW_TEST_KEY === "true",
  piiEncryptionKey: process.env.PII_ENCRYPTION_KEY,
  piiEncryptionKeys: process.env.PII_ENCRYPTION_KEYS,
  redisUrl: process.env.REDIS_URL,
  allowPlaintextPii: process.env.ALLOW_PLAINTEXT_PII,
});

export const ENV = parsedEnv;

/**
 * Fail-fast validation that runs once at server startup.
 * Blocks production launches with known-insecure defaults.
 */
export function validateProductionEnv(): void {
  if (ENV.isProduction) {
    const errors: string[] = [];
    const warnings: string[] = [];

    if (!ENV.cookieSecret || ENV.cookieSecret === KNOWN_DEV_JWT_SECRET) {
      errors.push(
        "JWT_SECRET must be set to a unique, secret value in production (the committed dev default is not safe)."
      );
    }
    if (ENV.cookieSecret.length < 32) {
      errors.push("JWT_SECRET must be at least 32 characters.");
    }
    // Authentication is satisfied either by Manus OAuth (OAUTH_SERVER_URL +
    // OWNER_OPEN_ID) or by the self-hosted local admin login
    // (ADMIN_USERNAME + ADMIN_PASSWORD_HASH). At least one path must be set.
    const localAuthConfigured = Boolean(
      ENV.adminUsername && ENV.adminPasswordHash
    );
    if (localAuthConfigured) {
      if (!ENV.adminPasswordHash.startsWith("scrypt$")) {
        errors.push(
          "ADMIN_PASSWORD_HASH must be generated by scripts/hashPassword.mjs (scrypt$… format)."
        );
      }
      if (ENV.adminUsername.length < 4) {
        warnings.push(
          "[SECURITY WARNING] ADMIN_USERNAME is shorter than 4 characters."
        );
      }
    }
    if (!ENV.ownerOpenId && !localAuthConfigured) {
      errors.push(
        "OWNER_OPEN_ID must be set in production so at least one admin exists (or configure ADMIN_USERNAME + ADMIN_PASSWORD_HASH for self-hosted login)."
      );
    }
    if (!ENV.oAuthServerUrl && !localAuthConfigured) {
      errors.push(
        "OAUTH_SERVER_URL must be set in production for authentication (or configure ADMIN_USERNAME + ADMIN_PASSWORD_HASH for self-hosted login)."
      );
    }
    if (!ENV.databaseUrl) {
      errors.push("DATABASE_URL must be set in production.");
    }

    // PII encryption: required in production (UU PDP No. 27/2022 hardening).
    // Set ALLOW_PLAINTEXT_PII=true only for transitional deployments where the
    // key cannot yet be provisioned — the warning keeps that decision visible.
    // PII_ENCRYPTION_KEYS (comma-separated ring, first = primary) takes
    // precedence; PII_ENCRYPTION_KEY remains the legacy single-key form.
    const piiRing = ENV.piiEncryptionKeys
      ? ENV.piiEncryptionKeys
          .split(",")
          .map(k => k.trim())
          .filter(Boolean)
      : [];
    const piiKeys =
      piiRing.length > 0
        ? piiRing
        : ENV.piiEncryptionKey
          ? [ENV.piiEncryptionKey]
          : [];
    if (piiKeys.length === 0) {
      if (ENV.allowPlaintextPii) {
        warnings.push(
          "[SECURITY WARNING] PII_ENCRYPTION_KEY / PII_ENCRYPTION_KEYS is not set but ALLOW_PLAINTEXT_PII=true — patient NIK and contact data will be stored UNENCRYPTED. Provision the key as soon as possible."
        );
      } else {
        errors.push(
          "PII_ENCRYPTION_KEY or PII_ENCRYPTION_KEYS must be set in production: patient NIK and contact data are encrypted at rest (UU PDP No. 27/2022). To launch without encryption during migration, set ALLOW_PLAINTEXT_PII=true."
        );
      }
    } else {
      piiKeys.forEach((key, i) => {
        if (key.length < 32) {
          const label =
            piiRing.length > 0
              ? `PII_ENCRYPTION_KEYS entry #${i + 1}`
              : "PII_ENCRYPTION_KEY";
          errors.push(
            `${label} must be at least 32 characters for sufficient entropy.`
          );
        }
      });
    }
    if (!ENV.redisUrl) {
      warnings.push(
        "[SCALABILITY WARNING] REDIS_URL is not set. Rate limiting uses in-memory state (resets on restart, not shared across instances). Implement the RateLimiter interface with a distributed store for multi-instance deployments."
      );
    }

    if (errors.length > 0) {
      throw new Error(
        `Production environment validation failed:\n${errors.join("\n")}`
      );
    }
    if (warnings.length > 0) {
      for (const w of warnings) {
        console.warn(
          JSON.stringify({
            timestamp: new Date().toISOString(),
            level: "warn",
            component: "env",
            message: w,
          })
        );
      }
    }
  }
}
